### ISSUE TITLE
Fix icon alignment

### ISSUE THREAD

**Issue by hckum** [pinformatics/MINDFIRL-userstudy#17]
1. Align large icons in userstudy screens. 
2. If not feasible, rollback to smaller icons.

**Comment by ilangurudev** [comment]
@Turmac @hckum Things to address regarding icons:

1. #34 
2. I think both the ID column and the name column use the same icon generation function. Which I think is creating problems. Not sure though. How much width does a number occupy as opposed to a character? Is it the same?
![screenshot-20180329143612-405x312](https://user-images.githubusercontent.com/20581414/38109676-94a62a60-335e-11e8-8c7e-548a86bd1def.png)
3. Whenever an icon is in the start or end, the alignment is awkward. 
![end](https://user-images.githubusercontent.com/20581414/38109618-56e7f5be-335e-11e8-87ef-4676e519918c.png)
![screenshot-20180329143356-140x103](https://user-images.githubusercontent.com/20581414/38109620-56f9ab1a-335e-11e8-8abd-7ab6901821e0.png)

**Comment by Turmac** [comment]
Yes, ID and name are using the same display function. At my environment character and digit has same width.

**Comment by ilangurudev** [comment]
Okay, so I looked at the icons at Blocker and they don't seem right. I think in addition to the screen res, the OS also matters (I remember having faced font issues in the first userstudy as well)?  What font are we using? 

Anyways @Turmac the best thing is to develop in Blocker and align it here so that it works. Maybe you could take a look at it at when you come and troubleshoot..
