### ISSUE TITLE
Section 2 batches of 36

### ISSUE THREAD

**Issue by Turmac** [pinformatics/MINDFIRL-userstudy#7]
After the pilot

**Comment by hckum** [comment]
* add section 2 questions
* making sure to reflect mode (4 modes)
* add/test data collection for section 2

**Comment by hckum** [comment]
close out section 2, by clicking on 2

**Comment by ilangurudev** [comment]
@hckum @Turmac 

1.I just noticed the meter gets reset after 36 questions in section 2 but there is no "break page" where we can say, "Now you're going to the next batch of 36". 
2. Also, we need the page count to read 1 **/6**

**Comment by ilangurudev** [comment]
@Turmac Please verify whether what I have done is right. 
@hckum You can check now

**Comment by Turmac** [comment]
It is correct but I don't recommend doing this by brute force.

**Comment by ilangurudev** [comment]
Haha, I don't recommend it either. It's just that we needed something to prototype and test and have a backup until we refactor it. Feel free to make it more efficient and change it as I am done with it for now.

**Comment by hckum** [comment]
@Turmac @ilangurudev 

Grading is not working for sure. Qinbo, please debug and let us know when done.

**Comment by ilangurudev** [comment]
@hckum Done. @Turmac , the grade final answer function was based on old urls ('section2') which has been changed to 'main_section'. So changing that worked. 

Letting you know so you'll change any other function based on old urls. 

Also, I changed the pull_data page such that it gives scores of all sections instead of just 1 and 2.
